name: SnowHalation
main: ifteam\SnowHalation\SnowHalation
version: 1.8-alpha
author: hm
api:
- 1.15.0
- 1.16.0
- 2.0.0
- 2.1.0
- 3.0.0

commands:
 snow:
   permission: snowhalation
   description: SnowHalation control commands
   usage: /snow

permissions:
 snowhalation:
  default: true
  description: Allows commands of SnowHalation
